import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import Module from 'node:module'
import {readFileSync,readdirSync} from 'node:fs'
import path from 'node:path'
import {randomUUID} from 'node:crypto'
import {EmbeddedPool} from './helpers/pglite-pool.mjs'
const require=createRequire(import.meta.url)
const {PrismaClient}=require('@prisma/client'),{PrismaPg}=require('@prisma/adapter-pg')
const pool=new EmbeddedPool(),db=new PrismaClient({adapter:new PrismaPg(pool),transactionOptions:{timeout:30000,maxWait:30000}})
let actor=null
const previous=Module._load
Module._load=function(id,parent,main){
 if(id==='@/lib/prisma')return {prisma:db}
 if(id==='@/lib/session')return {requireUser:async()=>{if(!actor)throw Response.json({},{status:401});return {user:actor}}}
 if(id==='next/headers')return {headers:async()=>new Headers()}
 if(id==='@/lib/auth')return {auth:{api:{getSession:async()=>actor?{user:actor}:null}}}
 return previous.call(this,id,parent,main)
}
const text=require('../app/api/conversations/[id]/route.ts'),share=require('../app/api/conversations/[id]/shares/route.ts'),image=require('../app/api/conversations/[id]/images/route.ts')
const original=require('../app/api/conversations/[id]/messages/[messageId]/route.ts'),reaction=require('../app/api/conversations/[id]/messages/[messageId]/reaction/route.ts'),state=require('../app/api/conversations/[id]/message-state/route.ts')
const account=require('../app/api/me/route.ts'),accountExport=require('../app/api/me/export/route.ts')
const {hydrateMessageState}=require('../lib/chat-interactions.ts')
const as=id=>actor=id?{id,name:id,email:`${id}@test.invalid`}:null
const context=(id='ab',messageId)=>({params:Promise.resolve({id,messageId})})
const request=data=>new Request('https://test.invalid/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)})
const get=()=>new Request('https://test.invalid/api')
async function snapshot(){return {messages:await db.directMessage.count(),notifications:await db.notification.count(),xp:await db.xPEvent.count(),unread:await db.directMessage.count({where:{readAt:null}}),last:(await db.conversationThread.findUnique({where:{id:'ab'}})).lastMessageAt?.toISOString()??null}}
async function send(content,replyToId,key=randomUUID()){const response=await text.POST(request({content,replyToId,clientMessageId:key}),context());return {response,body:await response.json(),key}}
async function react(emoji,messageId='source'){return reaction.PUT(request({emoji}),context('ab',messageId))}
test('reply and reaction lifecycle on isolated PostgreSQL with real routes and migrations',async t=>{
 try{
  for(const folder of readdirSync('prisma/migrations').sort()){
   if(folder==='migration_lock.toml')continue
   if(folder==='20261005040000_add_chat_replies_reactions')await pool.db.exec(`INSERT INTO "user" (id,name,email,"updatedAt") VALUES ('legacy-a','A','legacy-a@test.invalid',NOW()),('legacy-b','B','legacy-b@test.invalid',NOW()); INSERT INTO conversation_thread (id,"userAId","userBId","updatedAt") VALUES ('legacy-thread','legacy-a','legacy-b',NOW()); INSERT INTO direct_message (id,"conversationId","senderId",content,type) VALUES ('legacy-message','legacy-thread','legacy-a','Old message','text');`)
   await pool.db.exec(readFileSync(path.join('prisma/migrations',folder,'migration.sql'),'utf8'))
  }
  for(const id of ['a','b','c','d'])await db.user.create({data:{id,name:id,email:`${id}@test.invalid`,language:id==='b'?'zh':'en'}})
  for(const [id,userAId,userBId] of [['ab','a','b'],['ac','a','c'],['cd','c','d']])await db.conversationThread.create({data:{id,userAId,userBId}})
  await db.directMessage.create({data:{id:'source',conversationId:'ab',senderId:'b',content:'你好🪐'.repeat(100)}})
  await db.directMessage.create({data:{id:'other-source',conversationId:'ab',senderId:'a',content:'Another source'}})
  await db.directMessage.create({data:{id:'foreign',conversationId:'cd',senderId:'c',content:'FOREIGN SECRET'}})
  await db.community.create({data:{id:'galaxy',slug:'quote-galaxy',name:'Quoted galaxy'}})
  let reply,sharedSource,imageSource
  await t.test('additive migration preserves old messages with empty interaction state',async()=>{const row=await db.directMessage.findUnique({where:{id:'legacy-message'}});assert.equal(row.content,'Old message');assert.equal(row.replyToId,null);assert.equal(row.reactionVersion,0);assert.equal(await db.directMessageReaction.count(),0)})
  await t.test('unauthenticated and nonparticipant reads/mutations fail closed',async()=>{as(null);assert.equal((await original.GET(get(),context('ab','source'))).status,401);assert.equal((await react('👍')).status,401);as('c');assert.equal((await original.GET(get(),context('ab','source'))).status,404);assert.equal((await react('👍')).status,404);assert.equal((await state.POST(request({ids:['source']}),context())).status,404)})
  await t.test('source and state reads never mark read, notify or change activity',async()=>{as('a');const before=await snapshot();assert.equal((await original.GET(get(),context('ab','source'))).status,200);assert.equal((await state.POST(request({ids:['source']}),context())).status,200);assert.deepEqual(await snapshot(),before)})
  await t.test('reply sends a normal message with a bounded current excerpt and one notice',async()=>{as('a');const before=await snapshot();reply=await send('A reply','source');assert.equal(reply.response.status,201);assert.equal(reply.body.type,'text');assert.equal(reply.body.quote.available,true);assert.equal(reply.body.quote.id,'source');assert.equal([...reply.body.quote.excerpt].length,160);assert.ok(reply.body.quote.excerpt.startsWith('你好🪐'));const row=await db.directMessage.findUnique({where:{id:reply.body.id}});assert.equal(row.replyToId,'source');assert.equal(row.content,'A reply');const after=await snapshot();assert.equal(after.messages,before.messages+1);assert.equal(after.notifications,before.notifications+1)})
  await t.test('text retries compare quote identity and produce no second effects',async()=>{as('a');const before=await snapshot();assert.equal((await send('A reply','source',reply.key)).response.status,200);assert.equal((await send('A reply','other-source',reply.key)).response.status,409);assert.equal((await send('A reply',null,reply.key)).response.status,409);assert.deepEqual(await snapshot(),before)})
  await t.test('foreign/missing quote targets and copied snapshots cannot be supplied',async()=>{as('a');const before=await snapshot();assert.equal((await send('Bad','foreign')).response.status,404);assert.equal((await send('Bad','missing')).response.status,404);assert.equal((await text.POST(request({content:'Bad',replyToId:'source',quote:{excerpt:'forged'}}),context())).status,400);assert.equal((await original.GET(get(),context('ab','foreign'))).status,404);assert.deepEqual(await snapshot(),before)})
  await t.test('replying to a reply hydrates one level only',async()=>{as('a');const nested=await send('Nested reply',reply.body.id);assert.equal(nested.response.status,201);assert.equal(nested.body.quote.excerpt,'A reply');assert.ok(!('quote' in nested.body.quote));assert.ok(!JSON.stringify(nested.body.quote).includes('你好'))})
  await t.test('share replies use generic quotations, and quote identity is part of share retries',async()=>{as('a');const key=randomUUID(),payload={kind:'galaxy',targetId:'galaxy',clientMessageId:key,replyToId:'source'};const response=await share.POST(request(payload),context());assert.equal(response.status,201);const message=await response.json();assert.equal(message.quote.type,'text');assert.equal((await share.POST(request(payload),context())).status,200);assert.equal((await share.POST(request({...payload,replyToId:'other-source'}),context())).status,409);const quoted=await send('Reply to a card',message.id);assert.equal(quoted.body.quote.type,'share');assert.ok(!('excerpt' in quoted.body.quote));assert.ok(!('href' in quoted.body.quote));assert.ok(!JSON.stringify(quoted.body.quote).includes('Quoted galaxy'))})
  await t.test('image replies and image quotations keep byte URLs out of quotes',async()=>{as('a');const attachment=randomUUID();await db.chatImage.create({data:{id:attachment,ownerId:'a',conversationId:'ab',objectKey:`chat-images/${attachment}.webp`,rawDigest:'fixture',width:8,height:8,bytes:16,ready:true,expiresAt:new Date(Date.now()+3600000)}});const payload={imageId:attachment,clientMessageId:randomUUID(),replyToId:'source'};const response=await image.POST(request(payload),context());assert.equal(response.status,201);imageSource=await response.json();assert.equal(imageSource.quote.type,'text');assert.equal((await image.POST(request(payload),context())).status,200);assert.equal((await image.POST(request({...payload,replyToId:null}),context())).status,409);const quoted=await send('About your photo',imageSource.id);assert.deepEqual(quoted.body.quote,{available:true,id:imageSource.id,fromId:'a',type:'image'});assert.ok(!JSON.stringify(quoted.body.quote).includes('imageId'));assert.ok(!JSON.stringify(quoted.body.quote).includes('/images/'))})
  await t.test('shared target privacy changes hide quotations without copied title or target references',async()=>{const planet=await db.planet.create({data:{userId:'b',name:'PRIVATE QUOTE PLANET'}});sharedSource=await db.directMessage.create({data:{conversationId:'ab',senderId:'b',type:'share',content:'',shareKind:'planet',shareTargetId:planet.id}});as('a');const quoted=await send('About this',sharedSource.id);assert.equal(quoted.body.quote.type,'share');await db.profile.create({data:{userId:'b',visibility:'PRIVATE'}});const response=await original.GET(get(),context('ab',quoted.body.id));assert.deepEqual((await response.json()).quote,{available:false});assert.equal((await send('New hidden quote',sharedSource.id)).response.status,404);assert.equal((await send('About this',sharedSource.id,quoted.key)).response.status,200);await db.follow.create({data:{followerId:'a',followingId:'b'}});assert.equal((await (await original.GET(get(),context('ab',quoted.body.id))).json()).quote.available,true);await db.follow.deleteMany({where:{followerId:'a'}});await db.profile.delete({where:{userId:'b'}})})
  await t.test('a blocked shared target hides its quotation without closing the participants thread',async()=>{
   const planet=await db.planet.create({data:{userId:'c',name:'THIRD PARTY SECRET'}}),source=await db.directMessage.create({data:{conversationId:'ab',senderId:'b',type:'share',content:'',shareKind:'planet',shareTargetId:planet.id}})
   as('a');const quoted=await send('A third-party share',source.id);assert.equal(quoted.body.quote.available,true)
   const block=await db.block.create({data:{blockerId:'c',blockedId:'a'}})
   const response=await original.GET(get(),context('ab',quoted.body.id));assert.equal(response.status,200);const result=await response.json();assert.deepEqual(result.quote,{available:false});assert.ok(!JSON.stringify(result).includes('THIRD PARTY SECRET'))
   await db.block.delete({where:{id:block.id}})
  })
  await t.test('forged stored cross-thread references remain unavailable on hydration',async()=>{const row=await db.directMessage.create({data:{conversationId:'ab',senderId:'a',content:'Context',replyToId:'foreign'}});as('a');const [hydrated]=await hydrateMessageState([row],actor);assert.deepEqual(hydrated.quote,{available:false});assert.ok(!JSON.stringify(hydrated).includes('FOREIGN SECRET'))})
  await t.test('missing originals keep placeholders and matching delivered retries still succeed',async()=>{as('a');const source=await db.directMessage.create({data:{conversationId:'ab',senderId:'b',content:'Will disappear'}}),sent=await send('Delivered',source.id);await db.directMessage.delete({where:{id:source.id}});const response=await send('Delivered',source.id,sent.key);assert.equal(response.response.status,200);assert.deepEqual(response.body.quote,{available:false});assert.equal((await send('New reply',source.id)).response.status,404)})
  await t.test('reaction creation/retry have no message, unread, XP or activity effects',async()=>{as('a');const before=await snapshot();let response=await react('👍');assert.equal(response.status,200);let result=await response.json();assert.equal(result.reactionVersion,1);assert.deepEqual(result.reactions,[{emoji:'👍',count:1,mine:true}]);response=await react('👍');result=await response.json();assert.equal(result.reactionVersion,1);assert.equal(await db.directMessageReaction.count({where:{messageId:'source',userId:'a'}}),1);assert.deepEqual(await snapshot(),before)})
  await t.test('two participant reactions aggregate counts without actor identities',async()=>{as('b');const result=await (await react('👍')).json();assert.equal(result.reactionVersion,2);assert.deepEqual(result.reactions,[{emoji:'👍',count:2,mine:true}]);assert.ok(!JSON.stringify(result).includes('userId'));as('a');assert.deepEqual((await (await original.GET(get(),context('ab','source'))).json()).reactions,[{emoji:'👍',count:2,mine:true}])})
  await t.test('replacement and clear affect only the actor; clearing retries preserve version',async()=>{as('a');let result=await (await react('❤️')).json();assert.equal(result.reactionVersion,3);assert.deepEqual(result.reactions,[{emoji:'👍',count:1,mine:false},{emoji:'❤️',count:1,mine:true}]);result=await (await react(null)).json();assert.equal(result.reactionVersion,4);assert.deepEqual(result.reactions,[{emoji:'👍',count:1,mine:false}]);assert.equal((await (await react(null)).json()).reactionVersion,4);assert.equal(await db.directMessageReaction.count({where:{messageId:'source',userId:'b'}}),1)})
  await t.test('reaction API validates allowlist, strict body and same-thread resource',async()=>{as('a');assert.equal((await react('💩')).status,400);assert.equal((await react('❤')).status,400);assert.equal((await reaction.PUT(request({emoji:'👍',userId:'b'}),context('ab','source'))).status,400);assert.equal((await react('👍','foreign')).status,404);assert.equal((await reaction.PUT(request({emoji:'👍'}),context('ac','source'))).status,404)})
  await t.test('reaction quota blocks changes but permits already confirmed desired state',async()=>{as('a');await react('✨');await db.rateLimitBucket.updateMany({where:{bucketKey:'MESSAGE_REACTION:a'},data:{count:120}});const version=(await db.directMessage.findUnique({where:{id:'source'}})).reactionVersion;assert.equal((await react('✨')).status,200);assert.equal((await react(null)).status,429);assert.equal((await db.directMessage.findUnique({where:{id:'source'}})).reactionVersion,version);await db.rateLimitBucket.deleteMany({where:{bucketKey:'MESSAGE_REACTION:a'}})})
  await t.test('history refresh is bounded, scoped and includes current quotation/reaction state',async()=>{as('a');const response=await state.POST(request({ids:['source',reply.body.id,'foreign']}),context()),result=await response.json();assert.equal(response.status,200);assert.equal(result.messages.length,2);assert.equal(result.messages.find(row=>row.id==='source').reactions.length,2);assert.equal(result.messages.find(row=>row.id===reply.body.id).quote.available,true);assert.ok(!JSON.stringify(result).includes('FOREIGN SECRET'));assert.equal((await state.POST(request({ids:Array(101).fill('source')}),context())).status,400)})
  await t.test('bidirectional blocks deny quotes, originals, refresh and reactions including retries',async()=>{for(const [blockerId,blockedId] of [['a','b'],['b','a']]){const row=await db.block.create({data:{blockerId,blockedId}});for(const id of ['a','b']){as(id);assert.equal((await react('✨')).status,404);assert.equal((await original.GET(get(),context('ab','source'))).status,404);assert.equal((await state.POST(request({ids:['source']}),context())).status,404);assert.equal((await send('Blocked','source')).response.status,403)}await db.block.delete({where:{id:row.id}})}})
  await t.test('message export includes references and own reactions only',async()=>{as('a');const result=await (await accountExport.GET()).json(),exported=result.directMessages.find(row=>row.conversationId==='ab').messages;assert.equal(exported.find(row=>row.id===reply.body.id).replyToId,'source');assert.deepEqual(exported.find(row=>row.id==='source').reactions.map(row=>row.emoji),['✨']);assert.ok(exported.every(row=>!('quote' in row)));assert.ok(exported.flatMap(row=>row.reactions).every(row=>!('userId' in row)))})
  await t.test('physical source deletion cascades reactions while quotation context stays',async()=>{const source=await db.directMessage.create({data:{conversationId:'ab',senderId:'a',content:'Temporary'}});as('a');await react('👍',source.id);const quoted=await send('Still here',source.id);await db.directMessage.delete({where:{id:source.id}});assert.equal(await db.directMessageReaction.count({where:{messageId:source.id}}),0);assert.deepEqual((await (await original.GET(get(),context('ab',quoted.body.id))).json()).quote,{available:false})})
  await t.test('self-delete removes own reactions and advances version; old quotes remain readable',async()=>{const before=(await db.directMessage.findUnique({where:{id:'source'}})).reactionVersion;as('b');assert.equal((await account.DELETE(request({confirm:true}))).status,200);assert.equal(await db.directMessageReaction.count({where:{userId:'b'}}),0);assert.equal((await db.directMessage.findUnique({where:{id:'source'}})).reactionVersion,before+1);as('a');const result=await (await original.GET(get(),context('ab','source'))).json();assert.deepEqual(result.reactions,[{emoji:'✨',count:1,mine:true}]);assert.equal((await (await original.GET(get(),context('ab',reply.body.id))).json()).quote.available,true);assert.equal((await react('👍')).status,404);assert.equal((await send('Archived','source')).response.status,404);as('b');assert.equal((await original.GET(get(),context('ab','source'))).status,404)})
  await t.test('database constraints reject unsupported emoji and self quotation',async()=>{await assert.rejects(db.directMessageReaction.create({data:{messageId:'source',userId:'a',emoji:'invalid'}}));await assert.rejects(db.directMessage.create({data:{id:'self-quote',conversationId:'ac',senderId:'a',content:'Invalid',replyToId:'self-quote'}}))})
 }finally{await db.$disconnect();await pool.end();Module._load=previous}
})
