import type { PlanetProfile } from '@/types/planet'

// --- Mock planet pool ---------------------------------------------------------
// 12 diverse planets covering all mood / style / lifestyle combinations.
// These serve the /stream page and resonance matching engine.

export const mockPlanets: PlanetProfile[] = [
  {
    id: 'p-aelion',
    name: 'Aelion-42',
    avatarSymbol: '⊙',
    tagline: 'The universe holds its breath before I write',
    role: 'resonator',
    mood: 'melancholic',
    style: 'fractured',
    lifestyle: 'solitary',
    coreThemes: ['night & silence', 'memory', 'dream logic', 'emotional texture'],
    contentFragments: [
      'There are words I keep returning to without knowing why.',
      'The 3am version of me writes things I cannot claim in daylight.',
      'Memory isn\'t stored  -  it\'s rebuilt each time, and each time it lies.',
    ],
    visual: {
      coreColor: '#818cf8',
      accentColor: '#6366f1',
      ringStyle: 'broken',
      surfaceStyle: 'cracked',
      satelliteCount: 3,
      size: 'lg',
    },
    cognitiveAxes: { abstract: 72, introspective: 88 },
    emotionalBars: [
      { label: 'Depth',     value: 88, color: '#a78bfa' },
      { label: 'Warmth',    value: 38, color: '#f97316' },
      { label: 'Clarity',   value: 30, color: '#60a5fa' },
      { label: 'Resonance', value: 74, color: '#34d399' },
    ],
    createdAt: '2026-01-14T03:22:00Z',
    userId: 'usr_aelion',
    location: 'Shanghai · former French Concession',
    languages: ['中文', 'English', 'Français'],
    communicationStyle: 'poetic',
    activeStatus: 'drifting',
    galaxyIds: ['slow-thinkers', 'threshold-states'],
    culturalTags: ['Murakami', 'Satie', 'Wong Kar-wai', 'post-rock', 'lucid dreaming'],
    travelCities: ['Kyoto', 'Paris', 'Reykjavik'],
    musicTaste: ['Mogwai', 'Ólafur Arnalds', '朴树', 'ambient drone'],
    bookTaste: ['Borges', 'Clarice Lispector', '余华', 'poetry collections'],
    filmTaste: ['In the Mood for Love', 'Stalker', 'Yi Yi'],
    matchPreference: 'complementary',
    explorationTraces: [
      { label: 'Night writers',  planetType: 'melancholic-solitary', count: 12, color: '#818cf8', recentAt: '2026-03-28T02:00:00Z' },
      { label: 'Memory keepers', planetType: 'calm-rooted',          count: 7,  color: '#a78bfa', recentAt: '2026-03-25T22:15:00Z' },
      { label: 'Dream drifters', planetType: 'mixed-nomadic',        count: 5,  color: '#c4b5fd', recentAt: '2026-03-21T18:40:00Z' },
      { label: 'Quiet builders', planetType: 'cold-solitary',        count: 3,  color: '#60a5fa', recentAt: '2026-03-15T11:00:00Z' },
    ],
  },

  {
    id: 'p-kindus',
    name: 'Kindus-17',
    avatarSymbol: '◉',
    tagline: 'Momentum is my native language',
    role: 'resonator',
    mood: 'intense',
    style: 'fluid',
    lifestyle: 'communal',
    coreThemes: ['inner structure', 'solitude & connection', 'visual sensation'],
    contentFragments: [
      'I build things to understand them.',
      'Systems reveal what conversations hide.',
      'Every framework is a kind of prayer to order.',
    ],
    visual: {
      coreColor: '#f97316',
      accentColor: '#fb923c',
      ringStyle: 'double',
      surfaceStyle: 'crystalline',
      satelliteCount: 4,
      size: 'lg',
    },
    cognitiveAxes: { abstract: 55, introspective: 30 },
    emotionalBars: [
      { label: 'Depth',     value: 55, color: '#a78bfa' },
      { label: 'Warmth',    value: 82, color: '#f97316' },
      { label: 'Clarity',   value: 78, color: '#60a5fa' },
      { label: 'Resonance', value: 60, color: '#34d399' },
    ],
    createdAt: '2026-01-18T11:05:00Z',
    userId: 'usr_kindus',
    location: 'Shenzhen · Nanshan',
    languages: ['zh', 'en'],
    galaxyIds: ['signal-noise', 'threshold-states'],
    culturalTags: ['Bauhaus', 'Brian Eno', 'Stripe Press', 'Figma', 'systems design'],
    travelCities: ['Berlin', 'San Francisco', 'Singapore'],
    matchPreference: 'similar',
  },

  {
    id: 'p-sorvae',
    name: 'Sorvae-88',
    avatarSymbol: '◈',
    tagline: 'I map the interior so others can find their way',
    role: 'resonator',
    mood: 'calm',
    style: 'minimal',
    lifestyle: 'rooted',
    coreThemes: ['emotional texture', 'inner structure', 'solitude & connection'],
    contentFragments: [
      'Stillness is not emptiness. It is a kind of attention.',
      'I write in short sentences because each one should be able to stand alone.',
      'Clarity is a form of care.',
    ],
    visual: {
      coreColor: '#60a5fa',
      accentColor: '#93c5fd',
      ringStyle: 'single',
      surfaceStyle: 'smooth',
      satelliteCount: 1,
      size: 'md',
    },
    cognitiveAxes: { abstract: 40, introspective: 58 },
    emotionalBars: [
      { label: 'Depth',     value: 62, color: '#a78bfa' },
      { label: 'Warmth',    value: 58, color: '#f97316' },
      { label: 'Clarity',   value: 88, color: '#60a5fa' },
      { label: 'Resonance', value: 70, color: '#34d399' },
    ],
    createdAt: '2026-02-01T08:30:00Z',
    userId: 'usr_sorvae',
    location: 'Chengdu · Qingyang',
    languages: ['zh', 'en', 'ja'],
    galaxyIds: ['slow-thinkers', 'warm-frequency'],
    culturalTags: ['Stoic philosophy', 'Tarkovsky', 'Claude Debussy', 'Ursula K. Le Guin', 'wabi-sabi'],
    travelCities: ['Kyoto', 'Lisbon', 'Edinburgh'],
    matchPreference: 'mixed',
  },

  {
    id: 'p-noctaris',
    name: 'Noctaris-5',
    avatarSymbol: '○',
    tagline: 'Pure structure, zero noise',
    role: 'resonator',
    mood: 'cold',
    style: 'minimal',
    lifestyle: 'solitary',
    coreThemes: ['inner structure', 'night & silence'],
    contentFragments: [
      'Every argument is a graph. I trace edges until the cycle breaks.',
      'Emotion is information. Process it; don\'t perform it.',
      'The most interesting question is always: what are the axioms?',
    ],
    visual: {
      coreColor: '#94a3b8',
      accentColor: '#64748b',
      ringStyle: 'single',
      surfaceStyle: 'smooth',
      satelliteCount: 0,
      size: 'sm',
    },
    cognitiveAxes: { abstract: 95, introspective: 35 },
    emotionalBars: [
      { label: 'Depth',     value: 40, color: '#a78bfa' },
      { label: 'Warmth',    value: 18, color: '#f97316' },
      { label: 'Clarity',   value: 96, color: '#60a5fa' },
      { label: 'Resonance', value: 42, color: '#34d399' },
    ],
    createdAt: '2026-02-08T22:00:00Z',
    userId: 'usr_noctaris',
  },

  {
    id: 'p-lumira',
    name: 'Lumira-33',
    avatarSymbol: '◍',
    tagline: 'Stories find me; I just write them down',
    role: 'resonator',
    mood: 'mixed',
    style: 'dense',
    lifestyle: 'nomadic',
    coreThemes: ['memory', 'solitude & connection', 'emotional texture', 'visual sensation'],
    contentFragments: [
      'I collect stories the way others collect photographs.',
      'Every place I\'ve lived has left a layer, like sediment.',
      'I write so I don\'t mistake what I remember for what happened.',
    ],
    visual: {
      coreColor: '#34d399',
      accentColor: '#6ee7b7',
      ringStyle: 'double',
      surfaceStyle: 'nebulous',
      satelliteCount: 3,
      size: 'lg',
    },
    cognitiveAxes: { abstract: 48, introspective: 65 },
    emotionalBars: [
      { label: 'Depth',     value: 70, color: '#a78bfa' },
      { label: 'Warmth',    value: 72, color: '#f97316' },
      { label: 'Clarity',   value: 50, color: '#60a5fa' },
      { label: 'Resonance', value: 82, color: '#34d399' },
    ],
    createdAt: '2026-02-14T16:45:00Z',
    userId: 'usr_lumira',
    location: 'Nomadic · currently Chiang Mai',
    languages: ['中文', 'English', 'ภาษาไทย'],
    communicationStyle: 'reflective',
    activeStatus: 'active',
    galaxyIds: ['threshold-states', 'warm-frequency'],
    culturalTags: ['Calvino', 'lo-fi hip hop', 'analog photography', 'street food memoirs', 'Maugham'],
    travelCities: ['Chiang Mai', 'Tbilisi', 'Mexico City', 'Hanoi'],
    musicTaste: ['Khruangbin', 'Floating Points', 'lo-fi beats', 'Caribou'],
    bookTaste: ['Italo Calvino', 'W. Somerset Maugham', 'travel essays', 'oral histories'],
    filmTaste: ['Lost in Translation', 'Shoplifters', 'The Flavour of Green Tea over Rice'],
    matchPreference: 'complementary',
    explorationTraces: [
      { label: 'Warm nomads',     planetType: 'mixed-nomadic',     count: 18, color: '#34d399', recentAt: '2026-03-27T14:30:00Z' },
      { label: 'Story collectors', planetType: 'calm-rooted',      count: 9,  color: '#6ee7b7', recentAt: '2026-03-24T10:00:00Z' },
      { label: 'Visual thinkers', planetType: 'mixed-communal',    count: 6,  color: '#2dd4bf', recentAt: '2026-03-18T09:20:00Z' },
    ],
  },

  {
    id: 'p-driftan',
    name: 'Driftan-61',
    avatarSymbol: '⊛',
    tagline: 'Between languages, between worlds',
    role: 'resonator',
    mood: 'melancholic',
    style: 'fractured',
    lifestyle: 'nomadic',
    coreThemes: ['night & silence', 'memory', 'solitude & connection'],
    contentFragments: [
      'I think in three languages and feel in none of them.',
      'Distance is a skill I learned too young.',
      'Home is not a place. It\'s a particular quality of light.',
    ],
    visual: {
      coreColor: '#a78bfa',
      accentColor: '#c4b5fd',
      ringStyle: 'broken',
      surfaceStyle: 'nebulous',
      satelliteCount: 2,
      size: 'md',
    },
    cognitiveAxes: { abstract: 65, introspective: 80 },
    emotionalBars: [
      { label: 'Depth',     value: 84, color: '#a78bfa' },
      { label: 'Warmth',    value: 45, color: '#f97316' },
      { label: 'Clarity',   value: 38, color: '#60a5fa' },
      { label: 'Resonance', value: 76, color: '#34d399' },
    ],
    createdAt: '2026-02-20T02:10:00Z',
    userId: 'usr_driftan',
    location: 'Between cities · next: Taipei',
    languages: ['中文', 'English', 'Deutsch', '日本語'],
    communicationStyle: 'poetic',
    activeStatus: 'drifting',
    galaxyIds: ['threshold-states', 'slow-thinkers'],
    culturalTags: ['W.G. Sebald', 'Nils Frahm', 'Paul Auster', 'border cinema', 'drift writing'],
    travelCities: ['Taipei', 'Vienna', 'Montreal', 'Busan'],
    musicTaste: ['Nils Frahm', 'Max Richter', 'minimal piano', 'Icelandic post-classical'],
    bookTaste: ['W.G. Sebald', 'Paul Auster', 'Teju Cole', 'diasporic literature'],
    filmTaste: ['Wings of Desire', 'Last Year at Marienbad', 'Cafe Lumière'],
    matchPreference: 'mixed',
    explorationTraces: [
      { label: 'Border thinkers', planetType: 'melancholic-nomadic', count: 14, color: '#a78bfa', recentAt: '2026-03-28T23:00:00Z' },
      { label: 'Language drifters', planetType: 'mixed-nomadic',     count: 8,  color: '#c4b5fd', recentAt: '2026-03-22T16:40:00Z' },
      { label: 'Quiet resonators', planetType: 'calm-solitary',      count: 4,  color: '#818cf8', recentAt: '2026-03-10T20:15:00Z' },
    ],
  },

  {
    id: 'p-calenvix',
    name: 'Calenvix-9',
    avatarSymbol: '◎',
    tagline: 'Chaos is my medium; pattern is my product',
    role: 'resonator',
    mood: 'intense',
    style: 'fluid',
    lifestyle: 'communal',
    coreThemes: ['inner structure', 'visual sensation', 'solitude & connection'],
    contentFragments: [
      'I need noise to find quiet inside myself.',
      'The party is where I go to be alone in a useful way.',
      'Creation happens in the friction between too much and too little.',
    ],
    visual: {
      coreColor: '#fbbf24',
      accentColor: '#fde68a',
      ringStyle: 'double',
      surfaceStyle: 'crystalline',
      satelliteCount: 4,
      size: 'xl',
    },
    cognitiveAxes: { abstract: 60, introspective: 45 },
    emotionalBars: [
      { label: 'Depth',     value: 58, color: '#a78bfa' },
      { label: 'Warmth',    value: 78, color: '#f97316' },
      { label: 'Clarity',   value: 52, color: '#60a5fa' },
      { label: 'Resonance', value: 68, color: '#34d399' },
    ],
    createdAt: '2026-03-01T19:30:00Z',
    userId: 'usr_calenvix',
  },

  {
    id: 'p-orbalin',
    name: 'Orbalin-27',
    avatarSymbol: '◑',
    tagline: 'What the body knows before the mind catches up',
    role: 'resonator',
    mood: 'calm',
    style: 'dense',
    lifestyle: 'rooted',
    coreThemes: ['emotional texture', 'memory', 'dream logic'],
    contentFragments: [
      'I process through movement. The writing comes after.',
      'Some truths only arrive when you\'re not looking for them.',
      'My best ideas come in water  -  showers, rivers, rain.',
    ],
    visual: {
      coreColor: '#60a5fa',
      accentColor: '#7dd3fc',
      ringStyle: 'single',
      surfaceStyle: 'nebulous',
      satelliteCount: 2,
      size: 'md',
    },
    cognitiveAxes: { abstract: 50, introspective: 70 },
    emotionalBars: [
      { label: 'Depth',     value: 72, color: '#a78bfa' },
      { label: 'Warmth',    value: 65, color: '#f97316' },
      { label: 'Clarity',   value: 55, color: '#60a5fa' },
      { label: 'Resonance', value: 78, color: '#34d399' },
    ],
    createdAt: '2026-03-05T07:15:00Z',
    userId: 'usr_orbalin',
  },

  {
    id: 'p-spirax',
    name: 'Spirax-14',
    avatarSymbol: '⊕',
    tagline: 'I unravel things to see if they hold',
    role: 'resonator',
    mood: 'cold',
    style: 'dense',
    lifestyle: 'solitary',
    coreThemes: ['inner structure', 'dream logic', 'night & silence'],
    contentFragments: [
      'I spend hours on a sentence that most people skip.',
      'Precision is not pedantry. It is respect for the reader.',
      'The question behind the question is the one worth asking.',
    ],
    visual: {
      coreColor: '#818cf8',
      accentColor: '#a5b4fc',
      ringStyle: 'broken',
      surfaceStyle: 'cracked',
      satelliteCount: 1,
      size: 'sm',
    },
    cognitiveAxes: { abstract: 85, introspective: 62 },
    emotionalBars: [
      { label: 'Depth',     value: 80, color: '#a78bfa' },
      { label: 'Warmth',    value: 25, color: '#f97316' },
      { label: 'Clarity',   value: 90, color: '#60a5fa' },
      { label: 'Resonance', value: 55, color: '#34d399' },
    ],
    createdAt: '2026-03-09T14:40:00Z',
    userId: 'usr_spirax',
  },

  {
    id: 'p-vaelith',
    name: 'Vaelith-50',
    avatarSymbol: '◌',
    tagline: 'Soft things endure the longest',
    role: 'resonator',
    mood: 'calm',
    style: 'minimal',
    lifestyle: 'rooted',
    coreThemes: ['emotional texture', 'visual sensation', 'solitude & connection'],
    contentFragments: [
      'I make things with my hands first, then find out what they mean.',
      'Tenderness is not weakness. It is precision in the direction of care.',
      'I return to the same three songs when the world is too loud.',
    ],
    visual: {
      coreColor: '#f9a8d4',
      accentColor: '#fbcfe8',
      ringStyle: 'single',
      surfaceStyle: 'smooth',
      satelliteCount: 2,
      size: 'md',
    },
    cognitiveAxes: { abstract: 35, introspective: 75 },
    emotionalBars: [
      { label: 'Depth',     value: 68, color: '#a78bfa' },
      { label: 'Warmth',    value: 88, color: '#f97316' },
      { label: 'Clarity',   value: 60, color: '#60a5fa' },
      { label: 'Resonance', value: 85, color: '#34d399' },
    ],
    createdAt: '2026-03-12T10:20:00Z',
    userId: 'usr_vaelith',
    location: 'Hangzhou · 西湖 side',
    languages: ['中文', 'English'],
    communicationStyle: 'reflective',
    activeStatus: 'quiet',
    galaxyIds: ['warm-frequency', 'slow-thinkers'],
    culturalTags: ['Georgia O\'Keeffe', 'Chopin', 'slow cinema', 'handmade ceramics', 'poetry'],
    travelCities: ['Kyoto', 'Lisbon', 'Chengdu'],
    musicTaste: ['Chopin', 'Satie', '陈粒', 'ambient folk'],
    bookTaste: ['Mary Oliver', 'Sei Shōnagon', 'Jane Kenyon', 'short form poetry'],
    filmTaste: ['Autumn Sonata', 'An Elephant Sitting Still', 'Certified Copy'],
    matchPreference: 'similar',
    explorationTraces: [
      { label: 'Tender makers',   planetType: 'calm-rooted',         count: 10, color: '#f9a8d4', recentAt: '2026-03-26T18:00:00Z' },
      { label: 'Quiet observers', planetType: 'melancholic-solitary', count: 6,  color: '#fbcfe8', recentAt: '2026-03-20T11:30:00Z' },
      { label: 'Warm introverts', planetType: 'calm-solitary',       count: 4,  color: '#fca5a5', recentAt: '2026-03-12T09:45:00Z' },
    ],
  },

  {
    id: 'p-novaxis',
    name: 'Novaxis-3',
    avatarSymbol: '◆',
    tagline: 'The edge is where the interesting things live',
    role: 'resonator',
    mood: 'intense',
    style: 'fractured',
    lifestyle: 'nomadic',
    coreThemes: ['dream logic', 'visual sensation', 'inner structure'],
    contentFragments: [
      'I am drawn to things that don\'t fit categories.',
      'Every discipline is a lens; I keep switching.',
      'Borders are where cultures do their most interesting thinking.',
    ],
    visual: {
      coreColor: '#c084fc',
      accentColor: '#d8b4fe',
      ringStyle: 'double',
      surfaceStyle: 'nebulous',
      satelliteCount: 3,
      size: 'lg',
    },
    cognitiveAxes: { abstract: 78, introspective: 50 },
    emotionalBars: [
      { label: 'Depth',     value: 65, color: '#a78bfa' },
      { label: 'Warmth',    value: 60, color: '#f97316' },
      { label: 'Clarity',   value: 55, color: '#60a5fa' },
      { label: 'Resonance', value: 72, color: '#34d399' },
    ],
    createdAt: '2026-03-15T21:55:00Z',
    userId: 'usr_novaxis',
  },

  {
    id: 'p-elarith',
    name: 'Elarith-77',
    avatarSymbol: '◐',
    tagline: 'I am building the map as I walk',
    role: 'resonator',
    mood: 'mixed',
    style: 'fluid',
    lifestyle: 'communal',
    coreThemes: ['memory', 'emotional texture', 'solitude & connection', 'visual sensation'],
    contentFragments: [
      'I write to people, not about them.',
      'Connection is the only project I\'m always working on.',
      'Every conversation leaves a residue I carry forward.',
    ],
    visual: {
      coreColor: '#2dd4bf',
      accentColor: '#5eead4',
      ringStyle: 'none',
      surfaceStyle: 'nebulous',
      satelliteCount: 3,
      size: 'lg',
    },
    cognitiveAxes: { abstract: 45, introspective: 55 },
    emotionalBars: [
      { label: 'Depth',     value: 60, color: '#a78bfa' },
      { label: 'Warmth',    value: 90, color: '#f97316' },
      { label: 'Clarity',   value: 58, color: '#60a5fa' },
      { label: 'Resonance', value: 92, color: '#34d399' },
    ],
    createdAt: '2026-03-18T13:00:00Z',
    userId: 'usr_elarith',
  },
]

/** Get a planet by its id */
export function getPlanetById(id: string): PlanetProfile | undefined {
  return mockPlanets.find((p) => p.id === id)
}
