import type { RegionSuggestion } from './region-search'

// Common translated city names supplement the upstream local/EN/FR/DE index.
// The canonical value remains shared with English searches and matching.
const cities = [
  ['Paris','FR','巴黎'], ['Lyon','FR','里昂'], ['Marseille','FR','马赛|馬賽'], ['Nice','FR','尼斯'], ['Toulouse','FR','图卢兹|圖盧茲'], ['Bordeaux','FR','波尔多|波爾多'], ['Lille','FR','里尔|里爾'], ['Strasbourg','FR','斯特拉斯堡'], ['Nantes','FR','南特'], ['Montpellier','FR','蒙彼利埃'],
  ['London','GB','伦敦|倫敦'], ['Manchester','GB','曼彻斯特|曼徹斯特'], ['Edinburgh','GB','爱丁堡|愛丁堡'], ['Dublin','IE','都柏林'], ['Berlin','DE','柏林'], ['Munich','DE','慕尼黑'], ['Frankfurt','DE','法兰克福|法蘭克福'], ['Hamburg','DE','汉堡|漢堡'], ['Cologne','DE','科隆'], ['Amsterdam','NL','阿姆斯特丹'], ['Rotterdam','NL','鹿特丹'], ['Brussels','BE','布鲁塞尔|布魯塞爾'], ['Madrid','ES','马德里|馬德里'], ['Barcelona','ES','巴塞罗那|巴塞羅那'], ['Lisbon','PT','里斯本'], ['Rome','IT','罗马|羅馬'], ['Milan','IT','米兰|米蘭'], ['Venice','IT','威尼斯'], ['Florence','IT','佛罗伦萨|佛羅倫薩'], ['Zurich','CH','苏黎世|蘇黎世'], ['Geneva','CH','日内瓦|日內瓦'], ['Vienna','AT','维也纳|維也納'], ['Prague','CZ','布拉格'], ['Warsaw','PL','华沙|華沙'], ['Budapest','HU','布达佩斯|布達佩斯'], ['Copenhagen','DK','哥本哈根'], ['Stockholm','SE','斯德哥尔摩|斯德哥爾摩'], ['Oslo','NO','奥斯陆|奧斯陸'], ['Helsinki','FI','赫尔辛基|赫爾辛基'], ['Athens','GR','雅典'], ['Istanbul','TR','伊斯坦布尔|伊斯坦堡'],
  ['Beijing','CN','北京'], ['Shanghai','CN','上海'], ['Guangzhou','CN','广州|廣州'], ['Shenzhen','CN','深圳'], ['Chengdu','CN','成都'], ['Chongqing','CN','重庆|重慶'], ['Hangzhou','CN','杭州'], ['Nanjing','CN','南京'], ['Suzhou','CN','苏州|蘇州'], ['Wuhan','CN','武汉|武漢'], ['Tianjin','CN','天津'], ["Xi'an",'CN','西安'], ['Changsha','CN','长沙|長沙'], ['Zhengzhou','CN','郑州|鄭州'], ['Qingdao','CN','青岛|青島'], ['Dalian','CN','大连|大連'], ['Shenyang','CN','沈阳|瀋陽'], ['Harbin','CN','哈尔滨|哈爾濱'], ['Jinan','CN','济南|濟南'], ['Xiamen','CN','厦门|廈門'], ['Fuzhou','CN','福州'], ['Kunming','CN','昆明'], ['Nanning','CN','南宁|南寧'], ['Guiyang','CN','贵阳|貴陽'], ['Haikou','CN','海口'], ['Sanya','CN','三亚|三亞'], ['Ningbo','CN','宁波|寧波'], ['Wenzhou','CN','温州|溫州'], ['Wuxi','CN','无锡|無錫'], ['Hefei','CN','合肥'], ['Nanchang','CN','南昌'], ['Taiyuan','CN','太原'], ['Shijiazhuang','CN','石家庄|石家莊'], ['Changchun','CN','长春|長春'], ['Hohhot','CN','呼和浩特'], ['Lanzhou','CN','兰州|蘭州'], ['Xining','CN','西宁|西寧'], ['Yinchuan','CN','银川|銀川'], ['Urumqi','CN','乌鲁木齐|烏魯木齊'], ['Lhasa','CN','拉萨|拉薩'], ['Foshan','CN','佛山'], ['Dongguan','CN','东莞|東莞'], ['Zhuhai','CN','珠海'], ['Hong Kong','HK','香港'], ['Macau','MO','澳门|澳門'], ['Taipei','TW','台北|臺北'], ['Taichung','TW','台中|臺中'], ['Kaohsiung','TW','高雄'],
  ['Tokyo','JP','东京|東京'], ['Osaka','JP','大阪'], ['Kyoto','JP','京都'], ['Seoul','KR','首尔|首爾'], ['Busan','KR','釜山'], ['Singapore','SG','新加坡'], ['Bangkok','TH','曼谷'], ['Kuala Lumpur','MY','吉隆坡'], ['Hanoi','VN','河内|河內'], ['Ho Chi Minh City','VN','胡志明市'], ['Jakarta','ID','雅加达|雅加達'], ['Manila','PH','马尼拉|馬尼拉'], ['Dubai','AE','迪拜|杜拜'], ['Delhi','IN','德里'], ['Mumbai','IN','孟买|孟買'],
  ['New York','US','纽约|紐約'], ['Los Angeles','US','洛杉矶|洛杉磯'], ['San Francisco','US','旧金山|舊金山|三藩市'], ['Seattle','US','西雅图|西雅圖'], ['Boston','US','波士顿|波士頓'], ['Chicago','US','芝加哥'], ['Washington','US','华盛顿|華盛頓'], ['Houston','US','休斯顿|休斯頓'], ['Toronto','CA','多伦多|多倫多'], ['Vancouver','CA','温哥华|溫哥華'], ['Montreal','CA','蒙特利尔|蒙特利爾'], ['Ottawa','CA','渥太华|渥太華'], ['Sydney','AU','悉尼|雪梨'], ['Melbourne','AU','墨尔本|墨爾本'], ['Brisbane','AU','布里斯班'], ['Perth','AU','珀斯'], ['Auckland','NZ','奥克兰|奧克蘭'], ['Wellington','NZ','惠灵顿|惠靈頓'], ['Cairo','EG','开罗|開羅'], ['Cape Town','ZA','开普敦|開普敦'], ['Johannesburg','ZA','约翰内斯堡|約翰內斯堡'], ['São Paulo','BR','圣保罗|聖保羅'], ['Rio de Janeiro','BR','里约热内卢|里約熱內盧'], ['Buenos Aires','AR','布宜诺斯艾利斯|布宜諾斯艾利斯'], ['Mexico City','MX','墨西哥城'],
] as const

export function chineseRegionSuggestions(query: string): RegionSuggestion[] {
  if (!/\p{Script=Han}/u.test(query)) return []
  const q = query.trim().replace(/市$/u, '')
  if (!q) return []
  return cities.filter(([, , aliases]) => aliases.split('|').some(name => name.startsWith(q))).slice(0,6).map(([city,country,aliases]) => ({ value: `${city}, ${country}`, label: `${aliases.split('|')[0]} · ${city}, ${country}` }))
}
export function searchableRegionQuery(query: string) { return query.length >= 2 || /\p{Script=Han}/u.test(query) }
