import Link from 'next/link'
import type { ReactNode } from 'react'

export const metadata = { title: 'Privacy Policy — Gravity Souls' }

function Pending({ children }: { children: ReactNode }) {
  return (
    <span
      className="inline-block rounded-full px-2 py-0.5 text-[11px] font-medium align-middle"
      style={{
        color: 'var(--star)',
        border: '1px solid var(--border-soft)',
        background: 'rgba(255,255,255,0.03)',
      }}
    >
      Pending — {children}
    </span>
  )
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="mb-7 last:mb-0">
      <h2
        className="text-sm font-semibold mb-2"
        style={{ color: 'var(--foreground)' }}
      >
        {title}
      </h2>
      <div
        className="text-sm leading-relaxed space-y-2"
        style={{ color: 'var(--ink)', opacity: 0.82 }}
      >
        {children}
      </div>
    </section>
  )
}

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-20">
      <p
        className="text-eyebrow mb-4"
        style={{ letterSpacing: '0.12em' }}
      >
        Legal
      </p>
      <h1
        className="text-3xl font-semibold mb-6"
        style={{ color: 'var(--foreground)' }}
      >
        Privacy Policy
      </h1>
      <div
        className="rounded-2xl px-6 py-8 mb-8"
        style={{
          background: 'rgba(255,255,255,0.025)',
          border: '1px solid var(--border-soft)',
        }}
      >
        <p
          className="text-xs leading-relaxed mb-8"
          style={{ color: 'var(--ink)', opacity: 0.6 }}
        >
          This is a working draft, not a finalized legal document, written with GDPR in mind
          since Gravity Souls is France/EU-facing — nothing below has been reviewed by counsel
          or approved as our actual Privacy Policy yet. Sections marked Pending are still
          missing entirely; the rest is placeholder language subject to change. Do not rely on
          this page.
        </p>

        <Section title="1. Data controller">
          <p>
            <Pending>legal entity name and address</Pending>
          </p>
        </Section>

        <Section title="2. What data we collect">
          <p>
            We collect the information you provide directly — your email address and account
            credentials, your profile (&ldquo;planet&rdquo;) details such as name, tagline,
            location, and interests, and the content you post and the messages you send to
            other members. We also collect data generated by using the service, such as your
            community memberships, follows, and activity timestamps.
          </p>
        </Section>

        <Section title="3. How we use it">
          <p>
            We use this data to operate the service: to create and display your profile, to
            connect you with communities and other members, to deliver messages and
            notifications, and to keep the platform safe (for example, handling reports and
            enforcing our Community Guidelines).
          </p>
        </Section>

        <Section title="4. Legal basis for processing">
          <p>
            <Pending>specific GDPR legal basis determination</Pending>
          </p>
        </Section>

        <Section title="5. Data retention">
          <p>
            <Pending>retention periods</Pending>
          </p>
        </Section>

        <Section title="6. Your rights">
          <p>
            Depending on your jurisdiction, you have rights to access, rectify, erase, and
            port your personal data. You can already exercise several of these directly from{' '}
            <strong>Settings</strong>: exporting a copy of your data, and permanently deleting
            your account and its associated private data.
          </p>
        </Section>

        <Section title="7. Data sharing and processors">
          <p>
            <Pending>processor list (hosting, email, and other third-party services)</Pending>
          </p>
        </Section>

        <Section title="8. International data transfers">
          <p>
            <Pending>international data transfer details</Pending>
          </p>
        </Section>

        <Section title="9. Cookies">
          <p>
            Gravity Souls uses essential session cookies required to keep you signed in and to
            remember your language preference.{' '}
            <Pending>any additional cookie/analytics disclosure</Pending>
          </p>
        </Section>

        <Section title="10. Contact / Data Protection contact">
          <p>
            <Pending>contact email</Pending>
          </p>
        </Section>
      </div>
      <Link
        href="/"
        className="text-sm transition-colors"
        style={{ color: 'var(--star)', textDecoration: 'none' }}
      >
        ← Return to the universe
      </Link>
    </main>
  )
}
