ALTER TABLE "community"
 ADD COLUMN "region" TEXT NOT NULL DEFAULT '',
 ADD COLUMN "languages" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
 ADD COLUMN "interestTags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
 ADD COLUMN "connectionGoals" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
 ADD COLUMN "gatheringPreferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "event"
 ADD COLUMN "languages" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
 ADD COLUMN "interestTags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
 ADD COLUMN "connectionGoals" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
 ADD COLUMN "gatheringPreferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
